### ISSUE TITLE
could not run with config.ini

### ISSUE THREAD

**Issue by sea5kg** [shipko/ctf-attack-defense#10]
```
$ python3 main.py init config.ini 
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    from classes.flags import Flags
  File "/home/evgenii/develop/ctfight/ctf-attack-defense.git/classes/flags.py", line 11, in <module>
    from classes.configsource.configjson import ConfigJson
ImportError: No module named 'classes.configsource'
```

**Comment by shipko** [comment]
Немного поменялась структура.
Напишу в ридми позже. И да, ini файлы пока не поддерживаем

**Comment by sea5kg** [comment]
Блин я ж просил оставить ini. - Там комментарии можно оставлять! да и вообще попроще редактировать

**Comment by sea5kg** [comment]
Ну или его какой нибудь аналог

**Comment by shipko** [comment]
Хочу попробовать использовать какой-то новый формат. Типа продвинутый json.
С комментариями и т.д.

**Comment by sea5kg** [comment]
Тогда уж просто можно .py сделать со всеми настройками и коментариями
