### ISSUE TITLE
Please create LICENSE file

### ISSUE THREAD

**Issue by sea5kg** [shipko/ctf-attack-defense#14]
Please create LICENSE file

Example:

https://github.com/SibirCTF/2016-service-loogles/blob/master/LICENSE

**Comment by odinje** [comment]
Hi, would it be possible to add a license or get permissions to use this framework? We would love to use it at our school.

**Comment by shipko** [comment]
Hi! Of course.
License will be added in 2 days

**Comment by shipko** [comment]
Done
License GNU GPL v3.0
